# Generated by Django 5.2.5 on 2025-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='origin_city_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
