# Generated by Django 5.2.5 on 2025-08-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_country_origin_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='origin_city_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
